config/routes.rb
Rails.application.routes.draw do

  resources :messages
    root 'client#default', :as => :root

    get 'client/login', :as => :client_login
    get 'client/sign_up', :as => :client_signup
    get 'client/checkout', :as => :client_checkout
    get 'client/products', :as => :client_products
    get 'client/single_product', :as => :client_single_product
    get 'client/default', :as => :client_dashboard
    get 'client/offers'
    get 'contact_us' => 'static_pages#contact_us', :as => :contact_us
    get 'static_pages/contact_us'
    post 'client/make_order' => 'client#make_order'

    get 'admin/dashboard', :as => :admin_dashboard

    namespace :admin do
        resources :categories
        resources :products
        resources :carts, only: [:index, :show]
        resources :orders, only: [:index]
        resources :offers
    end

    devise_for :users
    resources :users
    resources :orders
    resources :offers, only: [:index]

end

app/models/admin/cart.rb
module Admin
    class Cart < ActiveRecord::Base
        belongs_to :user
        has_many :orders

        def sum_pharmacy
            orderAll = orders()
            sum = 0
            orderAll.each do |order|
                sum += (Product.find(order.product_id).price_pharmacy * order.quantity)
            end
            return sum
        end

        def sum_population
            orderAll = orders()
            sum = 0
            orderAll.each do |order|
                sum += (Product.find(order.product_id).price_population * order.quantity)
            end
            return sum
        end
    end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    belongs_to :user
    has_many :orders

    def sum_pharmacy
        orderAll = orders()
        sum = 0
        orderAll.each do |order|
            sum += (Product.find(order.product_id).price_pharmacy * order.quantity)
        end
        return sum
    end

    def sum_population
        orderAll = orders()
        sum = 0
        orderAll.each do |order|
            sum += (Product.find(order.product_id).price_population * order.quantity)
        end
        return sum
    end
end

app/controllers/admin/carts_controller.rb
module Admin
    class CartsController < AdminController
        before_action :set_cart, only: [:show, :edit, :update, :destroy]

        # GET /carts
        # GET /carts.json
        def index
            @carts = Cart.where(:placed => true)
        end

        # GET /carts/1
        # GET /carts/1.json
        def show
            @orders = Order.where(:cart_id => @cart.id)
            @user = User.find(@cart.user_id)
        end

        # GET /carts/new
        def new
            @cart = Cart.new
            @string = 'أضف'
        end

        # GET /carts/1/edit
        def edit
            @string = 'تعديل'
        end

        # POST /carts
        # POST /carts.json
        def create
            @cart = Cart.new(cart_params)
            respond_to do |format|
                if @cart.save
                    format.html { redirect_to admin_carts_url, notice: 'Cart was successfully created.' }
                    format.json { render :show, status: :created, location: @cart }
                else
                    format.html { render :new }
                    format.json { render json: @cart.errors, status: :unprocessable_entity }
                end
            end
        end

        # PATCH/PUT /carts/1
        # PATCH/PUT /carts/1.json
        def update
            respond_to do |format|
                if @cart.update(cart_params)
                    format.html { redirect_to admin_carts_url, notice: 'Cart was successfully updated.' }
                    format.json { render :show, status: :ok, location: @cart }
                else
                    format.html { render :edit }
                    format.json { render json: @cart.errors, status: :unprocessable_entity }
                end
            end
        end

        # DELETE /carts/1
        # DELETE /carts/1.json
        def destroy
            @cart.destroy
            respond_to do |format|
                format.html { redirect_to admin_carts_url, notice: 'Cart was successfully destroyed.' }
                format.json { head :no_content }
            end
        end

        private
        # Use callbacks to share common setup or constraints between actions.
        def set_cart
            @cart = Cart.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def cart_params
            params.require(:admin_cart).permit(:user_id, :placed)
        end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_cart, only: [:show, :edit, :update, :destroy]

    # GET /carts
    # GET /carts.json
    def index
        @carts = Cart.where(:placed => true)
    end

    # GET /carts/1
    # GET /carts/1.json
    def show
        @orders = Order.where(:cart_id => @cart.id)
        @user = User.find(@cart.user_id)
    end

    # GET /carts/new
    def new
        @cart = Cart.new
        @string = 'أضف'
    end

    # GET /carts/1/edit
    def edit
        @string = 'تعديل'
    end

    # POST /carts
    # POST /carts.json
    def create
        @cart = Cart.new(cart_params)
        respond_to do |format|
            if @cart.save
                format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
                format.json { render :show, status: :created, location: @cart }
            else
                format.html { render :new }
                format.json { render json: @cart.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /carts/1
    # PATCH/PUT /carts/1.json
    def update
        respond_to do |format|
            if @cart.update(cart_params)
                format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
                format.json { render :show, status: :ok, location: @cart }
            else
                format.html { render :edit }
                format.json { render json: @cart.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /carts/1
    # DELETE /carts/1.json
    def destroy
        @cart.destroy
        respond_to do |format|
            format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
        @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
        params.require(:cart).permit(:user_id, :placed)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for @cart, :html => {:class => "form-horizontal cart"} do |f| %>

    <% if @cart.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title"><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being
                    saved:</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <% @cart.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label 'المُستخدم', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <%= f.text_field :user_id, :class => 'form-control' %>
        </div>
        <%= f.error_span(:user_id) %>
    </div>
    <div class="form-group">
        <%= f.label :placed, :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <select class="form-control" name="cart[placed]" id="cart_placed">
                <option value="true"
                        <% if @cart.placed == true %> selected
                        <% end %>>True
                </option>
                <option value="false"
                        <% if @cart.placed == false %> selected
                        <% end %>>False
                </option>
            </select>
        </div>
        <%= f.error_span(:placed) %>
    </div>

    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <%= f.submit @string, :class => 'btn btn-primary' %>
            <%= link_to 'إلغاء', carts_path, :class => 'btn btn-default' %>
        </div>
    </div>

<% end %>

app/views/carts/index.html.erb
<%- model_class = Cart -%>
<div class="page-header">
    <h1>الطلبات</h1>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i> <%= link_to 'Dashboard', :admin_dashboard %>
        </li>
        <li class="active">
            <i class="fa fa-table"></i> الطلبات
        </li>
    </ol>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>المُستخدم</th>
        <th>السعر للصيدليات</th>
        <th>السعر للجمهور</th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th>الإجراءات</th>
    </tr>
    </thead>
    <tbody>
    <% @carts.each do |cart| %>
        <tr>
            <td><%= cart.id %></td>
            <td><%= User.find(cart.user_id).name %></td>
            <td><%= cart.price_pharmacy %></td>
            <td><%= cart.price_population %></td>

            <td><%= l cart.created_at %></td>
            <td>
                <%= link_to 'عرض التفاصيل', cart_path(cart), :class => 'btn btn-default' %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>

<script>
    $(function () {
        $(".table").dataTable({
            "language": {
                "url": "/lib/datatables/lang-ar.json"
            }
        });
    });
</script>

app/views/carts/show.html.erb
<%- model_class = Cart -%>
<div class="page-header">
    <h1>الطلب رقم <%= @cart.id %></h1>
</div>

<dl class="dl-horizontal">
    <dt><strong>المُستخدم:</strong></dt>
    <dd>
        <div class="row">
            <br>
            الرتبة: <%= @user.position %> <br>
            الإسم: <%= @user.name %> <br>
            العنوان: <%= @user.address %> <br>
            الرقم الأرضي: <%= @user.landline_number %> <br>
            رقم المحمول: <%= @user.mobile_number %> <br>
            محل العمل: <%= @user.workplace %> <br>
        </div>

    </dd>

    <hr>

    <dt><strong>المُشترىات:</strong></dt>
    <dd>
        <br>
        <div class="row">
            <div class="col-lg-10">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>الصنف</th>
                        <th>الكمية</th>
                        <th>السعر للصيدليات</th>
                        <th>السعر للجمهور</th>
                        <th><%= model_class.human_attribute_name(:created_at) %></th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @orders.each do |order| %>
                        <tr>
                            <td><%= order.id %></td>
                            <td><%= Product.find(order.product_id).name %></td>
                            <td><%= order.quantity %></td>
                            <td><%= order.price_pharmacy %></td>
                            <td><%= order.price_population %></td>
                            <td><%= l order.created_at %></td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </dd>

    <hr>

    <dt><strong>السعر الكُلّي للصيدليات:</strong></dt>
    <dd><%= @cart.price_pharmacy %></dd>
    <dt><strong>السعر الكُلّي للجمهور:</strong></dt>
    <dd><%= @cart.price_population %></dd>

    <hr>

</dl>


<%= link_to 'الرحوع', admin_carts_path, :class => 'btn btn-default' %>

<script>
    $(function () {
        $(".table").dataTable({
            "lengthMenu": [5, 10, 25],
            "language": {
                "url": "/lib/datatables/lang-ar.json"
            }
        });
    });
</script>