config/routes.rb
Rails.application.routes.draw do

  resources :messages
    root 'client#default', :as => :root

    get 'client/login', :as => :client_login
    get 'client/sign_up', :as => :client_signup
    get 'client/checkout', :as => :client_checkout
    get 'client/products', :as => :client_products
    get 'client/single_product', :as => :client_single_product
    get 'client/default', :as => :client_dashboard
    get 'client/offers'
    get 'contact_us' => 'static_pages#contact_us', :as => :contact_us
    get 'static_pages/contact_us'
    post 'client/make_order' => 'client#make_order'

    get 'admin/dashboard', :as => :admin_dashboard

    namespace :admin do
        resources :categories
        resources :products
        resources :carts, only: [:index, :show]
        resources :orders, only: [:index]
        resources :offers
    end

    devise_for :users
    resources :users
    resources :orders
    resources :offers, only: [:index]

end

app/models/admin/offer.rb
module Admin
    class Offer < ActiveRecord::Base
    end
end

app/models/offer.rb
class Offer < ActiveRecord::Base
end

app/controllers/admin/offers_controller.rb
module Admin
    class OffersController < AdminController
        before_action :set_offer, only: [:show, :edit, :update, :destroy]

        # GET /offers
        # GET /offers.json
        def index
            @offers = Offer.all
        end

        # GET /offers/1
        # GET /offers/1.json
        def show
        end

        # GET /offers/new
        def new
            @offer = Offer.new
            @string = 'أضف'
        end

        # GET /offers/1/edit
        def edit
            @string = 'تعديل'
        end

        # POST /offers
        # POST /offers.json
        def create
            @offer = Offer.new(offer_params)

            respond_to do |format|
                if @offer.save
                    format.html { redirect_to admin_offers_url, notice: 'Offer was successfully created.' }
                    format.json { render :show, status: :created, location: @offer }
                else
                    format.html { render :new }
                    format.json { render json: @offer.errors, status: :unprocessable_entity }
                end
            end
        end

        # PATCH/PUT /offers/1
        # PATCH/PUT /offers/1.json
        def update
            respond_to do |format|
                if @offer.update(offer_params)
                    format.html { redirect_to admin_offers_url, notice: 'Offer was successfully updated.' }
                    format.json { render :show, status: :ok, location: @offer }
                else
                    format.html { render :edit }
                    format.json { render json: @offer.errors, status: :unprocessable_entity }
                end
            end
        end

        # DELETE /offers/1
        # DELETE /offers/1.json
        def destroy
            @offer.destroy
            respond_to do |format|
                format.html { redirect_to admin_offers_url, notice: 'Offer was successfully destroyed.' }
                format.json { head :no_content }
            end
        end

        private
        # Use callbacks to share common setup or constraints between actions.
        def set_offer
            @offer = Offer.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def offer_params
            params.require(:admin_offer).permit(:title, :description, :start, :end)
        end
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
    before_action :set_offer, only: [:show, :edit, :update, :destroy]

    # GET /offers
    # GET /offers.json
    def index
        @offers = Offer.all
    end

    # GET /offers/1
    # GET /offers/1.json
    def show
    end

    # GET /offers/new
    def new
        @offer = Offer.new
        @string = 'أضف'
    end

    # GET /offers/1/edit
    def edit
        @string = 'تعديل'
    end

    # POST /offers
    # POST /offers.json
    def create
        @offer = Offer.new(offer_params)

        respond_to do |format|
            if @offer.save
                format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
                format.json { render :show, status: :created, location: @offer }
            else
                format.html { render :new }
                format.json { render json: @offer.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /offers/1
    # PATCH/PUT /offers/1.json
    def update
        respond_to do |format|
            if @offer.update(offer_params)
                format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
                format.json { render :show, status: :ok, location: @offer }
            else
                format.html { render :edit }
                format.json { render json: @offer.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /offers/1
    # DELETE /offers/1.json
    def destroy
        @offer.destroy
        respond_to do |format|
            format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
        @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
        params.require(:offer).permit(:title, :description, :start, :end)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for @offer, :html => {:class => "form-horizontal offer"} do |f| %>

    <% if @offer.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title"><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being
                    saved:</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <% @offer.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label 'العنوان', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <%= f.text_field :title, :class => 'form-control' %>
        </div>
        <%= f.error_span(:title) %>
    </div>
    <div class="form-group">
        <%= f.label 'الشرح', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <%= f.text_field :description, :class => 'form-control' %>
        </div>
        <%= f.error_span(:description) %>
    </div>
    <div class="form-group">
        <%= f.label 'إبتداءًا من', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <%= f.text_field :start, :class => 'form-control' %>
        </div>
        <%= f.error_span(:start) %>
    </div>
    <div class="form-group">
        <%= f.label 'إنتهاءًا في', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <%= f.text_field :end, :class => 'form-control' %>
        </div>
        <%= f.error_span(:end) %>
    </div>

    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-5">
            <%= f.submit @string, :class => 'btn btn-primary' %>
            <%= link_to 'إلغاء', offers_path, :class => 'btn btn-default' %>
        </div>
    </div>

<% end %>

app/views/offers/index.html.erb
<%- model_class = Offer -%>
<div class="page-header" dir="rtl ">
  <h1>العروض</h1>
  <ol class="breadcrumb">
    <li>
      <i class="fa fa-dashboard"></i> <%= link_to 'Dashboard', :admin_dashboard %>
    </li>
    <li class="active">
      <i class="fa fa-table"></i> العروض
    </li>
  </ol>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>العنوان</th>
    <th>الشرح</th>
    <th>إبتداءًا من</th>
    <th>إنتهاءًا في</th>
    <th>الإجراءات</th>
  </tr>
  </thead>
  <tbody>
  <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.id %></td>
        <td><%= offer.title %></td>
        <td><%= offer.description %></td>
        <td><%= offer.start ? (l offer.start) : '' %></td>
        <td><%= offer.end ? (l offer.end) : '' %></td>
        <td><%= l offer.created_at %></td>
        <td>
          <%= link_to 'تعديل', edit_offer_path(offer), :class => 'btn btn-xs btn-default' %>

          <%= link_to 'مسح', offer_path(offer), :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'أضف عرض', new_admin_offer_path, :class => 'btn btn-primary' %>

<script>
  $(function () {
    $(".table").dataTable({
      "language": {
        "url": "/lib/datatables/lang-ar.json"
      }
    });
  });
</script>

app/views/offers/show.html.erb
<%- model_class = Offer -%>
<div class="page-header">
    <h1>العرض رقم <%= @offer.id %></h1>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i> <%= link_to 'Dashboard', :admin_dashboard %>
        </li>
        <li>
            <i class="fa fa-table"></i> <%= link_to 'العروض', offers_path %>
        </li>
        <li class="active">
            العرض رقم <%= @offer.id %>
        </li>
    </ol>
</div>

<dl class="dl-horizontal">
    <dt><strong>العنوان:</strong></dt>
    <dd><%= @offer.title %></dd>
    <dt><strong>الشرح:</strong></dt>
    <dd><%= @offer.description %></dd>
    <dt><strong>إبتداءًا من:</strong></dt>
    <dd><%= @offer.start %></dd>
    <dt><strong>إنتهاءًا في:</strong></dt>
    <dd><%= @offer.end %></dd>
</dl>

<%= link_to 'الرجوع', offers_path, :class => 'btn btn-default' %>
<%= link_to 'تعديل', edit_offer_path(@offer), :class => 'btn btn-default' %>
<%= link_to 'مسح', offer_path(@offer), :method => 'delete',
    :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
    :class => 'btn btn-danger' %>