config/routes.rb
Rails.application.routes.draw do

  resources :messages
    root 'client#default', :as => :root

    get 'client/login', :as => :client_login
    get 'client/sign_up', :as => :client_signup
    get 'client/checkout', :as => :client_checkout
    get 'client/products', :as => :client_products
    get 'client/single_product', :as => :client_single_product
    get 'client/default', :as => :client_dashboard
    get 'client/offers'
    get 'contact_us' => 'static_pages#contact_us', :as => :contact_us
    get 'static_pages/contact_us'
    post 'client/make_order' => 'client#make_order'

    get 'admin/dashboard', :as => :admin_dashboard

    namespace :admin do
        resources :categories
        resources :products
        resources :carts, only: [:index, :show]
        resources :orders, only: [:index]
        resources :offers
    end

    devise_for :users
    resources :users
    resources :orders
    resources :offers, only: [:index]

end

app/models/admin/category.rb
module Admin
    class Category < ActiveRecord::Base

        has_many :products

        has_attached_file :photo

        validates_attachment_content_type :photo,
            :content_type => ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

    end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

  has_attached_file :photo

  validates_attachment_content_type :photo,
                                    :content_type => ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  def products_of_children
    children_products = Product.none
    Category.where(parent_id: id()).each do |category|
      children_products += (category.products)
    end
    children_products

  end

end

app/controllers/admin/categories_controller.rb
module Admin
    class CategoriesController < AdminController
        before_action :set_category, only: [:show, :edit, :update, :destroy]

        # GET /categories
        # GET /categories.json
        def index
            if params[:parent_id]
                @categories = Category.where(:parent_id => params[:parent_id])
            else
                @categories = Category.where(:parent_id => nil)
            end

        end

        # GET /categories/1
        # GET /categories/1.json
        def show
        end

        # GET /categories/new
        def new
            @category = Category.new
            @string = 'أضف'
        end

        # GET /categories/1/edit
        def edit
            @string = 'تعديل'
        end

        # POST /categories
        # POST /categories.json
        def create
            @category = Category.new(category_params)

            respond_to do |format|
                if @category.save
                    format.html { redirect_to '/admin/categories', notice: 'Category was successfully created.' }
                    format.json { render :show, status: :created, location: @category }
                else
                    format.html { render :new }
                    format.json { render json: @category.errors, status: :unprocessable_entity }
                end
            end
        end

        # PATCH/PUT /categories/1
        # PATCH/PUT /categories/1.json
        def update
            respond_to do |format|
                if @category.update(category_params)
                    format.html { redirect_to '/admin/categories', notice: 'Category was successfully updated.' }
                    format.json { render :show, status: :ok, location: @category }
                else
                    format.html { render :edit }
                    format.json { render json: @category.errors, status: :unprocessable_entity }
                end
            end
        end

        # DELETE /categories/1
        # DELETE /categories/1.json
        def destroy
            @category.destroy
            respond_to do |format|
                format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
                format.json { head :no_content }
            end
        end

        private
        # Use callbacks to share common setup or constraints between actions.
        def set_category
            @category = Category.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def category_params
            params.require(:admin_category).permit(:parent_id, :name, :comments, :photo)
        end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for @category,:url => url_for(:controller => 'admin/categories', :action => 'create'),:method => 'POST' , :html => {:class =>
"form-horizontal category"} do |f| %>

    <% if @category.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from
                    being saved:</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <% @category.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>


    <div class="form-group">
        <%= f.label 'الفئة الأم', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <%= f.collection_select :parent_id, Category.where(:parent_id => nil), :id, :name, {:include_blank => 'No Parent', :value => :parent_id}, {:class => 'form-control'} %>
        </div>
        <%= f.error_span(:parent_id) %>
    </div>

    <div class="form-group">
        <%= f.label 'الإسم', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <%= f.text_field :name, :class => 'form-control' %>
        </div>
        <%= f.error_span(:name) %>
    </div>
    <div class="form-group">
        <%= f.label 'التعليقات', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <%= f.text_field :comments, :class => 'form-control' %>
        </div>
        <%= f.error_span(:comments) %>
    </div>

    <div class="form-group">
        <%= f.label 'الصورة', :class => 'control-label col-lg-2' %>
        <div class="col-lg-5">
            <label class="btn btn-default btn-file">
                أضف صورة
                <%= f.file_field :photo, :style => 'display: none;' %>
            </label>
        </div>
        <%= f.error_span(:photo) %>
    </div>

    <% if @category.photo_file_name %>
        <div class="form-group">
            <%= f.label :photo, "الصورة الحالية", :class => 'control-label col-lg-2' %>
            <div class="col-lg-5">
                <%= @category.photo_file_name %>
            </div>
        </div>
    <% end %>

    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-5">
            <%= f.submit @string, :class => 'btn btn-primary' %>
            <%= link_to 'إلغاء', admin_categories_path, :class => 'btn btn-default' %>
        </div>
    </div>

<% end %>

<script>
    $('#category_parent_id').selectpicker({
        style: 'btn-default',
        size: 4
    });

</script>

app/views/admin/categories/edit.html.erb
<%- model_class = Admin::Category -%>
<div class="page-header">
    <h1>تعديل فئة</h1>
</div>
<%= form_for @category,:url => url_for(:controller => 'admin/categories', :action => 'update'),:method => 'PATCH' ,:html =>
    {:class =>
         "form-horizontal category"} do |f| %>

    <% if @category.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from
              being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @category.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>


    <div class="form-group">
      <%= f.label 'الصنف الأم', :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.collection_select :parent_id, Category.all, :id, :name, {:include_blank => 'No Parent', :value => :parent_id}, {:class => 'form-control'} %>
      </div>
      <%= f.error_span(:parent_id) %>
    </div>

    <div class="form-group">
      <%= f.label 'الإسم', :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%= f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label 'التعليقات', :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.text_field :comments, :class => 'form-control' %>
      </div>
      <%= f.error_span(:comments) %>
    </div>

    <div class="form-group">
      <%= f.label 'الصورة', :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.file_field :photo, :class => 'form-control' %>
      </div>
      <%= f.error_span(:photo) %>
    </div>

    <% if @category.photo_file_name %>
        <div class="form-group">
          <%= f.label :photo, "الصورة الحالية", :class => 'control-label col-lg-2' %>
          <div class="col-lg-5">
            <%= @category.photo_file_name %>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-5">
        <%= f.submit @string, :class => 'btn btn-primary' %>
        <%= link_to 'إلغاء', admin_categories_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

<script>
  $('#category_parent_id').selectpicker({
    style: 'btn-default',
    size: 4
  });

</script>

app/views/admin/categories/index.html.erb
<%- model_class = Admin::Category -%>
<div class="page-header">
    <h1>الفئات</h1>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i> <%= link_to 'Dashboard', :admin_dashboard %>
        </li>
        <li class="active">
            <i class="fa fa-table"></i> الفئات
        </li>
    </ol>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>الفئة الأم</th>
        <th>الإسم</th>
        <th>التعليقات</th>
        <th>الصورة</th>
        <th>الإجراءات</th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
        <tr>
            <td><%= category.id %></td>
            <td><%= category.parent_id ? Category.find(category.parent_id).name : '' %></td>
            <td><%= category.name %></td>
            <td><%= category.comments %></td>
            <td><%= category.photo_file_name %></td>
            <td>
                <%= link_to 'تعديل', edit_admin_category_path(category), :class => 'btn btn-xs btn-default' %>

                <%= link_to 'التصنيفات', admin_categories_path(:parent_id => category.id), :class => 'btn btn-xs btn-default' %>

                <%= link_to 'أضف صنف', new_admin_product_path(:category_id => category.id), :class => 'btn btn-xs btn-default' %>

                <%= link_to 'الأصناف', admin_products_path(:category_id => category.id), :class => 'btn btn-xs btn-default' %>

                <%= link_to 'مسح', admin_category_path(category), :method => :delete,
                    :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure ?'))},
                    :class => 'btn btn-xs btn-danger'
                %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>

<%= link_to 'أضف فئة', new_admin_category_path, :class => 'btn btn-primary' %>

<script>
    $(function () {
        $(".table").dataTable({
            "language": {
                "url": "/lib/datatables/lang-ar.json"
            }
        });
    });
</script>

app/views/admin/categories/new.html.erb
<%- model_class = Admin::Category -%>
<div class="page-header">
    <h1>أضف فئة</h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/categories/show.html.erb
<%- model_class = Admin::Category -%>
<div class="page-header">
    <h1>الفئة رقم <%= @category.id %></h1>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i> <%= link_to 'Dashboard', :admin_dashboard %>
        </li>
        <li>
            <i class="fa fa-table"></i> <%= link_to 'الفئات', admin_categories_path %>
        </li>
        <li class="active">
            الفئة رقم <%= @category.id %>
        </li>
    </ol>
</div>

<dl class="dl-horizontal">
    <dt><strong>الفئة الأم:</strong></dt>
    <dd><%= @category.parent_id %></dd>
    <dt><strong>الإسم:</strong></dt>
    <dd><%= @category.name %></dd>
    <dt><strong>التعليقات:</strong></dt>
    <dd><%= @category.comments %></dd>
    <% if @category.photo_file_name %>
        <dt><strong>الصورة:</strong></dt>
        <dd><%= image_tag @category.photo.url %></dd>
    <% end %>
</dl>

<%= link_to 'الرحوع', admin_categories_path, :class => 'btn btn-default' %>
<%= link_to 'تعديل', edit_admin_category_path(@category), :class => 'btn btn-default' %>
<%= link_to 'مسح', admin_category_path(@category), :method => 'delete',
    :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
    :class => 'btn btn-danger' %>