config/routes.rb
Rails.application.routes.draw do

  resources :messages
    root 'client#default', :as => :root

    get 'client/login', :as => :client_login
    get 'client/sign_up', :as => :client_signup
    get 'client/checkout', :as => :client_checkout
    get 'client/products', :as => :client_products
    get 'client/single_product', :as => :client_single_product
    get 'client/default', :as => :client_dashboard
    get 'client/offers'
    get 'contact_us' => 'static_pages#contact_us', :as => :contact_us
    get 'static_pages/contact_us'
    post 'client/make_order' => 'client#make_order'

    get 'admin/dashboard', :as => :admin_dashboard

    namespace :admin do
        resources :categories
        resources :products
        resources :carts, only: [:index, :show]
        resources :orders, only: [:index]
        resources :offers
    end

    devise_for :users
    resources :users
    resources :orders
    resources :offers, only: [:index]

end

app/models/admin/product.rb
module Admin
    class Product < ActiveRecord::Base
        belongs_to :category
        has_attached_file :photo

        validates_attachment_content_type :photo,
            :content_type => ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
    end
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :category
    has_attached_file :photo

    validates_attachment_content_type :photo,
        :content_type => ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
end

app/controllers/admin/products_controller.rb
module Admin
    class ProductsController < AdminController
        before_action :set_product, only: [:show, :edit, :update, :destroy]

        # GET /products
        # GET /products.json
        def index
            if params[:category_id]
                @products = Category.find(params[:category_id]).products
            else
                @products = Product.all
            end
        end

        # GET /products/1
        # GET /products/1.json
        def show
        end

        # GET /products/new
        def new
            @product = Product.new
            @string = 'أضف'
        end

        # GET /products/1/edit
        def edit
            @string = 'تعديل'
        end

        # POST /products
        # POST /products.json
        def create
            @product = Product.new(product_params)

            respond_to do |format|
                if @product.save
                    format.html { redirect_to admin_products_url, notice: 'Product was successfully created.' }
                    format.json { render :show, status: :created, location: @product }
                else
                    format.html { render :new }
                    format.json { render json: @product.errors, status: :unprocessable_entity }
                end
            end
        end

        # PATCH/PUT /products/1
        # PATCH/PUT /products/1.json
        def update
            respond_to do |format|
                if @product.update(product_params)
                    format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully updated
.' }
                    format.json { render :show, status: :ok, location: @product }
                else
                    format.html { render :edit }
                    format.json { render json: @product.errors, status: :unprocessable_entity }
                end
            end
        end

        # DELETE /products/1
        # DELETE /products/1.json
        def destroy
            @product.destroy
            respond_to do |format|
                format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
                format.json { head :no_content }
            end
        end

        private
        # Use callbacks to share common setup or constraints between actions.
        def set_product
            @product = Product.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def product_params
            params.require(:admin_product).permit(:category_id, :name, :price_pharmacy, :price_population, :comments, :photo)
        end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for @product,:url => url_for(:controller => 'admin/products', :action => 'create'),:method => 'POST' ,:html =>
    {:class =>
                                                                                                    "form-horizontal product"} do |f| %>

    <% if @product.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from
              being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @product.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label 'الفئة', :class => 'control-label col-lg-2' %>
      <% if params[:category_id] %>
          <div class="col-lg-9">
            <%= f.label Category.find(params[:category_id]).name, :class => 'col-lg-2' %>
            <%= f.hidden_field :category_id, :value => params[:category_id] %>
          </div>
      <% else %>
          <div class="col-lg-9">
            <%= f.collection_select :category_id, Category.where.not(:parent_id => nil), :id, :name, {}, {:class => 'form-control'} %>
          </div>
      <% end %>
      <%= f.error_span(:category_id) %>
    </div>
    <div class="form-group">
      <%= f.label 'الإسم', :class => 'control-label col-lg-2' %>
      <div class="col-lg-9">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%= f.error_span(:name) %>
    </div>
    <div class="form-group">
        <%= f.label 'السعر للصيدليات', :class => 'control-label col-lg-2' %>
        <div class="col-lg-9">
            <%= f.number_field :price_pharmacy, :class => 'form-control' , :step => 'any' %>
        </div>
        <%= f.error_span(:price_pharmacy) %>
    </div>
    <div class="form-group">
        <%= f.label 'السعر للجمهور', :class => 'control-label col-lg-2' %>
        <div class="col-lg-9">
            <%= f.number_field :price_population, :class => 'form-control' , :step => 'any' %>
        </div>
        <%= f.error_span(:price_population) %>
    </div>
    <div class="form-group">
      <%= f.label 'التعليقات', :class => 'control-label col-lg-2' %>
      <div class="col-lg-9">
        <%= f.text_field :comments, :class => 'form-control' %>
      </div>
      <%= f.error_span(:comments) %>
    </div>

    <div class="form-group">
      <%= f.label 'الصورة', :class => 'control-label col-lg-2' %>
      <div class="col-lg-9">
        <label class="btn btn-default btn-file">
          أضف صورة
          <%= f.file_field :photo, :style => 'display: none;' %>
        </label>
      </div>
      <%= f.error_span(:photo) %>

    </div>

    <% if @product.photo_file_name %>
        <div class="form-group">

          <%= f.label :photo, "الصورة الحالية", :class => 'control-label col-lg-2' %>
          <div class="col-lg-9">
            <%= @product.photo_file_name %>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-9">
        <%= f.submit @string, :class => 'btn btn-primary' %>
        <%= link_to 'إلغاء', admin_products_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/admin/products/edit.html.erb
<%- model_class = Admin::Product -%>
<div class="page-header">
    <h1>تعديل صنف</h1>
</div>
<%= form_for @product,:url => url_for(:controller => 'admin/products', :action => 'update'),:method => 'PATCH' ,:html =>
    {:class =>
         "form-horizontal product"} do |f| %>

    <% if @product.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from
              being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @product.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label 'الصنف', :class => 'control-label col-lg-2' %>
      <% if params[:category_id] %>
          <div class="col-lg-9">
            <%= f.label Category.find(params[:category_id]).name, :class => 'col-lg-2' %>
            <%= f.hidden_field :category_id, :value => params[:category_id] %>
          </div>
      <% else %>
          <div class="col-lg-9">
            <%= f.collection_select :category_id, Category.all, :id, :name, {:class => 'form-control'} %>
          </div>
      <% end %>
      <%= f.error_span(:category_id) %>
    </div>
    <div class="form-group">
      <%= f.label 'الإسم', :class => 'control-label col-lg-2' %>
      <div class="col-lg-9">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%= f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label 'السعر للصيدليات', :class => 'control-label col-lg-2' %>
      <div class="col-lg-9">
        <%= f.number_field :price_pharmacy, :class => 'form-control' , :step => 'any' %>
      </div>
      <%= f.error_span(:price_pharmacy) %>
    </div>
    <div class="form-group">
      <%= f.label 'السعر للجمهور', :class => 'control-label col-lg-2' %>
      <div class="col-lg-9">
        <%= f.number_field :price_population, :class => 'form-control' , :step => 'any' %>
      </div>
      <%= f.error_span(:price_population) %>
    </div>
    <div class="form-group">
      <%= f.label 'التعليقات', :class => 'control-label col-lg-2' %>
      <div class="col-lg-9">
        <%= f.text_field :comments, :class => 'form-control' %>
      </div>
      <%= f.error_span(:comments) %>
    </div>

    <div class="form-group">
      <%= f.label 'الصورة', :class => 'control-label col-lg-2' %>
      <div class="col-lg-9">
        <%= f.file_field :photo, :class => 'form-control' %>
      </div>
      <%= f.error_span(:photo) %>

    </div>

    <% if @product.photo_file_name %>
        <div class="form-group">

          <%= f.label :photo, "الصورة الحالية", :class => 'control-label col-lg-2' %>
          <div class="col-lg-9">
            <%= @product.photo_file_name %>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-9">
        <%= f.submit @string, :class => 'btn btn-primary' %>
        <%= link_to 'إلغاء', admin_products_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/admin/products/index.html.erb
<%- model_class = Admin::Product -%>
<div class="page-header">
    <h1>الأصناف</h1>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i> <%= link_to 'Dashboard', :admin_dashboard %>
        </li>
        <li class="active">
            <i class="fa fa-table"></i> الأصناف
        </li>
    </ol>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>الفئة</th>
        <th>الإسم</th>
        <th>السعر للصيدليات</th>
        <th>السعر للجمهور</th>
        <th>التعليقات</th>
        <th>الصورة</th>
        <th>الإجراءات</th>
    </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
        <tr>
            <td><%= product.id %></td>
            <td><%= Category.find(product.category_id).name %></td>
            <td><%= product.name %></td>
            <td><%= product.price_pharmacy %></td>
            <td><%= product.price_population %></td>
            <td><%= product.comments %></td>
            <td><%= product.photo_file_name %></td>

            <td>
                <%= link_to 'تعديل', edit_admin_product_path(product), :class => 'btn btn-default btn-xs' %>

                <%= link_to 'مسح', admin_product_path(product), :method => :delete,
                    :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                    :class => 'btn btn-xs btn-danger' %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>

<%= link_to 'أضف صنف', new_admin_product_path, :class => 'btn btn-primary' %>

<script>
    $(function () {
        $(".table").dataTable({
            "language": {
                "url": "/lib/datatables/lang-ar.json"
            }
        });
    });
</script>

app/views/admin/products/new.html.erb
<%- model_class = Admin::Product -%>
<div class="page-header">
    <h1>أضف صنف</h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/products/show.html.erb
<%- model_class = Admin::Product -%>
<div class="page-header">
    <h1>الصنف رقم <%= @product.id %></h1>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i> <%= link_to 'Dashboard', :admin_dashboard %>
        </li>
        <li>
            <i class="fa fa-table"></i> <%= link_to 'الأصناف', admin_products_path %>
        </li>
        <li class="active">
            الصنف رقم <%= @product.id %>
        </li>
    </ol>
</div>

<dl class="dl-horizontal">
    <dt><strong>الفئة:</strong></dt>
    <dd><%= Category.find(@product.category_id).name %></dd>
    <dt><strong>الإسم:</strong></dt>
    <dd><%= @product.name %></dd>
    <dt><strong>السعر للصيدليات:</strong></dt>
    <dd><%= @product.price_pharmacy %></dd>
    <dt><strong>السعر للجمهور:</strong></dt>
    <dd><%= @product.price_population %></dd>
    <dt><strong>التعليقات:</strong></dt>
    <dd><%= @product.comments %></dd>
    <% if @product.photo_file_name %>
        <dt><strong>الصورة:</strong></dt>
        <dd><%= image_tag @product.photo.url %></dd>
    <% end %>
</dl>

<%= link_to 'الرحوع', admin_products_path, :class => 'btn btn-default' %>
<%= link_to 'تعديل', edit_admin_product_path(@product), :class => 'btn btn-default' %>
<%= link_to 'مسح', admin_product_path(@product), :method => 'delete',
    :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
    :class => 'btn btn-danger' %>